-- Create the properties table
create table public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price numeric,
  location text,
  image_url text,
  type text check (type in ('buy', 'rent')),
  bedrooms int,
  bathrooms int,
  size_m2 int
);

-- Turn on Row Level Security
alter table public.properties enable row level security;

-- Allow read access to everyone
create policy "Allow public read access"
  on public.properties for select
  using ( true );

-- Allow write access only to authenticated users
create policy "Allow authenticated insert"
  on public.properties for insert
  with check ( auth.role() = 'authenticated' );

create policy "Allow authenticated update"
  on public.properties for insert
  with check ( auth.role() = 'authenticated' );

create policy "Allow authenticated delete"
  on public.properties for delete
  using ( auth.role() = 'authenticated' );

-- STORAGE SETUP
-- You must manually create a bucket named 'images' in the Supabase Dashboard Storage section.
-- Then run these policies to allow access.

-- Allow public read access to images
create policy "Give public access to images"
on storage.objects for select
using ( bucket_id = 'images' );

-- Allow authenticated uploads
create policy "Allow authenticated uploads"
on storage.objects for insert
with check ( bucket_id = 'images' and auth.role() = 'authenticated' );
